[discovery]
    nodes = ["127.0.0.1:7171"]
[redis]
    network = "tcp"
    addr = "127.0.0.1:6379"
    active = 60000
    idle = 1024
    dialTimeout = "200ms"
    readTimeout = "500ms"
    writeTimeout = "500ms"
    idleTimeout = "120s"
    expire = "30m"
[collector]
    itvl = "3s"