// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
// v1.0.0
// protocol
type Proto struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver,proto3" json:"ver"`
	Op                   int32    `protobuf:"varint,2,opt,name=op,proto3" json:"op"`
	Seq                  int32    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body,proto3" json:"body"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proto) Reset()         { *m = Proto{} }
func (m *Proto) String() string { return proto.CompactTextString(m) }
func (*Proto) ProtoMessage()    {}
func (*Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proto.Unmarshal(m, b)
}
func (m *Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proto.Marshal(b, m, deterministic)
}
func (m *Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proto.Merge(m, src)
}
func (m *Proto) XXX_Size() int {
	return xxx_messageInfo_Proto.Size(m)
}
func (m *Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_Proto.DiscardUnknown(m)
}

var xxx_messageInfo_Proto proto.InternalMessageInfo

func (m *Proto) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Proto) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *Proto) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Proto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PushMsgReq struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	ProtoOp              int32    `protobuf:"varint,3,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}
func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (m *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(m, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *PushMsgReq) GetProtoOp() int32 {
	if m != nil {
		return m.ProtoOp
	}
	return 0
}

func (m *PushMsgReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type PushMsgReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReply) Reset()         { *m = PushMsgReply{} }
func (m *PushMsgReply) String() string { return proto.CompactTextString(m) }
func (*PushMsgReply) ProtoMessage()    {}
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}
func (m *PushMsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReply.Unmarshal(m, b)
}
func (m *PushMsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReply.Marshal(b, m, deterministic)
}
func (m *PushMsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReply.Merge(m, src)
}
func (m *PushMsgReply) XXX_Size() int {
	return xxx_messageInfo_PushMsgReply.Size(m)
}
func (m *PushMsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReply proto.InternalMessageInfo

type BroadcastReq struct {
	ProtoOp              int32    `protobuf:"varint,1,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Speed                int32    `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReq) Reset()         { *m = BroadcastReq{} }
func (m *BroadcastReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastReq) ProtoMessage()    {}
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}
func (m *BroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReq.Unmarshal(m, b)
}
func (m *BroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReq.Marshal(b, m, deterministic)
}
func (m *BroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReq.Merge(m, src)
}
func (m *BroadcastReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastReq.Size(m)
}
func (m *BroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReq proto.InternalMessageInfo

func (m *BroadcastReq) GetProtoOp() int32 {
	if m != nil {
		return m.ProtoOp
	}
	return 0
}

func (m *BroadcastReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

func (m *BroadcastReq) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type BroadcastReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReply) Reset()         { *m = BroadcastReply{} }
func (m *BroadcastReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastReply) ProtoMessage()    {}
func (*BroadcastReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}
func (m *BroadcastReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReply.Unmarshal(m, b)
}
func (m *BroadcastReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReply.Marshal(b, m, deterministic)
}
func (m *BroadcastReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReply.Merge(m, src)
}
func (m *BroadcastReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastReply.Size(m)
}
func (m *BroadcastReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReply proto.InternalMessageInfo

type BroadcastRoomReq struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRoomReq) Reset()         { *m = BroadcastRoomReq{} }
func (m *BroadcastRoomReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastRoomReq) ProtoMessage()    {}
func (*BroadcastRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}
func (m *BroadcastRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRoomReq.Unmarshal(m, b)
}
func (m *BroadcastRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRoomReq.Marshal(b, m, deterministic)
}
func (m *BroadcastRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRoomReq.Merge(m, src)
}
func (m *BroadcastRoomReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastRoomReq.Size(m)
}
func (m *BroadcastRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRoomReq proto.InternalMessageInfo

func (m *BroadcastRoomReq) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *BroadcastRoomReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type BroadcastRoomReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRoomReply) Reset()         { *m = BroadcastRoomReply{} }
func (m *BroadcastRoomReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastRoomReply) ProtoMessage()    {}
func (*BroadcastRoomReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}
func (m *BroadcastRoomReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRoomReply.Unmarshal(m, b)
}
func (m *BroadcastRoomReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRoomReply.Marshal(b, m, deterministic)
}
func (m *BroadcastRoomReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRoomReply.Merge(m, src)
}
func (m *BroadcastRoomReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastRoomReply.Size(m)
}
func (m *BroadcastRoomReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRoomReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRoomReply proto.InternalMessageInfo

type RoomsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomsReq) Reset()         { *m = RoomsReq{} }
func (m *RoomsReq) String() string { return proto.CompactTextString(m) }
func (*RoomsReq) ProtoMessage()    {}
func (*RoomsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}
func (m *RoomsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsReq.Unmarshal(m, b)
}
func (m *RoomsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsReq.Marshal(b, m, deterministic)
}
func (m *RoomsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsReq.Merge(m, src)
}
func (m *RoomsReq) XXX_Size() int {
	return xxx_messageInfo_RoomsReq.Size(m)
}
func (m *RoomsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsReq proto.InternalMessageInfo

type RoomsReply struct {
	Rooms                map[string]bool `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoomsReply) Reset()      { *m = RoomsReply{} }
func (*RoomsReply) ProtoMessage() {}
func (*RoomsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}
func (m *RoomsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsReply.Unmarshal(m, b)
}
func (m *RoomsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsReply.Marshal(b, m, deterministic)
}
func (m *RoomsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsReply.Merge(m, src)
}
func (m *RoomsReply) XXX_Size() int {
	return xxx_messageInfo_RoomsReply.Size(m)
}
func (m *RoomsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsReply.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsReply proto.InternalMessageInfo

func (m *RoomsReply) GetRooms() map[string]bool {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type OnlinesReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlinesReq) Reset()         { *m = OnlinesReq{} }
func (m *OnlinesReq) String() string { return proto.CompactTextString(m) }
func (*OnlinesReq) ProtoMessage()    {}
func (*OnlinesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}
func (m *OnlinesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlinesReq.Unmarshal(m, b)
}
func (m *OnlinesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlinesReq.Marshal(b, m, deterministic)
}
func (m *OnlinesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlinesReq.Merge(m, src)
}
func (m *OnlinesReq) XXX_Size() int {
	return xxx_messageInfo_OnlinesReq.Size(m)
}
func (m *OnlinesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlinesReq.DiscardUnknown(m)
}

var xxx_messageInfo_OnlinesReq proto.InternalMessageInfo

type OnlinesReply struct {
	HostOnline           int64            `protobuf:"varint,1,opt,name=hostOnline,proto3" json:"hostOnline,omitempty"`
	TcpOnline            int64            `protobuf:"varint,2,opt,name=tcpOnline,proto3" json:"tcpOnline,omitempty"`
	WsOnline             int64            `protobuf:"varint,3,opt,name=wsOnline,proto3" json:"wsOnline,omitempty"`
	RoomOnlines          map[string]int64 `protobuf:"bytes,4,rep,name=roomOnlines,proto3" json:"roomOnlines,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	MidOnlines           map[int64]int64  `protobuf:"bytes,5,rep,name=midOnlines,proto3" json:"midOnlines,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OnlinesReply) Reset()         { *m = OnlinesReply{} }
func (m *OnlinesReply) String() string { return proto.CompactTextString(m) }
func (*OnlinesReply) ProtoMessage()    {}
func (*OnlinesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}
func (m *OnlinesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlinesReply.Unmarshal(m, b)
}
func (m *OnlinesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlinesReply.Marshal(b, m, deterministic)
}
func (m *OnlinesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlinesReply.Merge(m, src)
}
func (m *OnlinesReply) XXX_Size() int {
	return xxx_messageInfo_OnlinesReply.Size(m)
}
func (m *OnlinesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlinesReply.DiscardUnknown(m)
}

var xxx_messageInfo_OnlinesReply proto.InternalMessageInfo

func (m *OnlinesReply) GetHostOnline() int64 {
	if m != nil {
		return m.HostOnline
	}
	return 0
}

func (m *OnlinesReply) GetTcpOnline() int64 {
	if m != nil {
		return m.TcpOnline
	}
	return 0
}

func (m *OnlinesReply) GetWsOnline() int64 {
	if m != nil {
		return m.WsOnline
	}
	return 0
}

func (m *OnlinesReply) GetRoomOnlines() map[string]int64 {
	if m != nil {
		return m.RoomOnlines
	}
	return nil
}

func (m *OnlinesReply) GetMidOnlines() map[int64]int64 {
	if m != nil {
		return m.MidOnlines
	}
	return nil
}

type MessagesReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesReq) Reset()         { *m = MessagesReq{} }
func (m *MessagesReq) String() string { return proto.CompactTextString(m) }
func (*MessagesReq) ProtoMessage()    {}
func (*MessagesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}
func (m *MessagesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesReq.Unmarshal(m, b)
}
func (m *MessagesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesReq.Marshal(b, m, deterministic)
}
func (m *MessagesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesReq.Merge(m, src)
}
func (m *MessagesReq) XXX_Size() int {
	return xxx_messageInfo_MessagesReq.Size(m)
}
func (m *MessagesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesReq proto.InternalMessageInfo

type MessagesReply struct {
	MsgStats             []*MsgStat `protobuf:"bytes,1,rep,name=msgStats,proto3" json:"msgStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessagesReply) Reset()         { *m = MessagesReply{} }
func (m *MessagesReply) String() string { return proto.CompactTextString(m) }
func (*MessagesReply) ProtoMessage()    {}
func (*MessagesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}
func (m *MessagesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesReply.Unmarshal(m, b)
}
func (m *MessagesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesReply.Marshal(b, m, deterministic)
}
func (m *MessagesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesReply.Merge(m, src)
}
func (m *MessagesReply) XXX_Size() int {
	return xxx_messageInfo_MessagesReply.Size(m)
}
func (m *MessagesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesReply.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesReply proto.InternalMessageInfo

func (m *MessagesReply) GetMsgStats() []*MsgStat {
	if m != nil {
		return m.MsgStats
	}
	return nil
}

type MsgStat struct {
	MsgType              int32    `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Speed                float64  `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgStat) Reset()         { *m = MsgStat{} }
func (m *MsgStat) String() string { return proto.CompactTextString(m) }
func (*MsgStat) ProtoMessage()    {}
func (*MsgStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}
func (m *MsgStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgStat.Unmarshal(m, b)
}
func (m *MsgStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgStat.Marshal(b, m, deterministic)
}
func (m *MsgStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStat.Merge(m, src)
}
func (m *MsgStat) XXX_Size() int {
	return xxx_messageInfo_MsgStat.Size(m)
}
func (m *MsgStat) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStat.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStat proto.InternalMessageInfo

func (m *MsgStat) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *MsgStat) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MsgStat) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func init() {
	proto.RegisterType((*Proto)(nil), "goim.comet.Proto")
	proto.RegisterType((*Empty)(nil), "goim.comet.Empty")
	proto.RegisterType((*PushMsgReq)(nil), "goim.comet.PushMsgReq")
	proto.RegisterType((*PushMsgReply)(nil), "goim.comet.PushMsgReply")
	proto.RegisterType((*BroadcastReq)(nil), "goim.comet.BroadcastReq")
	proto.RegisterType((*BroadcastReply)(nil), "goim.comet.BroadcastReply")
	proto.RegisterType((*BroadcastRoomReq)(nil), "goim.comet.BroadcastRoomReq")
	proto.RegisterType((*BroadcastRoomReply)(nil), "goim.comet.BroadcastRoomReply")
	proto.RegisterType((*RoomsReq)(nil), "goim.comet.RoomsReq")
	proto.RegisterType((*RoomsReply)(nil), "goim.comet.RoomsReply")
	proto.RegisterMapType((map[string]bool)(nil), "goim.comet.RoomsReply.RoomsEntry")
	proto.RegisterType((*OnlinesReq)(nil), "goim.comet.OnlinesReq")
	proto.RegisterType((*OnlinesReply)(nil), "goim.comet.OnlinesReply")
	proto.RegisterMapType((map[int64]int64)(nil), "goim.comet.OnlinesReply.MidOnlinesEntry")
	proto.RegisterMapType((map[string]int64)(nil), "goim.comet.OnlinesReply.RoomOnlinesEntry")
	proto.RegisterType((*MessagesReq)(nil), "goim.comet.MessagesReq")
	proto.RegisterType((*MessagesReply)(nil), "goim.comet.MessagesReply")
	proto.RegisterType((*MsgStat)(nil), "goim.comet.MsgStat")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 711 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xfe, 0x1d, 0xdb, 0xb9, 0x9c, 0xa4, 0xfd, 0xc3, 0x50, 0x05, 0xd7, 0xaa, 0x9a, 0xe2, 0x0d,
	0x41, 0xa2, 0xa9, 0x54, 0x84, 0xa8, 0x8a, 0xa8, 0x20, 0xa5, 0x12, 0x08, 0x45, 0xad, 0xa6, 0xac,
	0xd8, 0xe5, 0x32, 0xb8, 0x51, 0xe3, 0xcc, 0x24, 0xe3, 0x14, 0xf9, 0x01, 0x78, 0x07, 0x96, 0x3c,
	0x59, 0xb7, 0x48, 0x7d, 0x08, 0x84, 0xe6, 0x8c, 0xe3, 0x4b, 0x48, 0x69, 0xc5, 0xc6, 0x9a, 0xef,
	0xdc, 0xbe, 0x73, 0x8e, 0xe7, 0x1b, 0xa8, 0xf4, 0xc4, 0xa8, 0x2d, 0x66, 0x3c, 0xe4, 0x04, 0x7c,
	0x3e, 0x0a, 0xda, 0x03, 0x1e, 0xb0, 0xd0, 0xdd, 0xf5, 0x47, 0xe1, 0xc5, 0xbc, 0xaf, 0xd0, 0x9e,
	0xcf, 0x7d, 0xbe, 0x87, 0x21, 0xfd, 0xf9, 0x17, 0x44, 0x08, 0xf0, 0xa4, 0x53, 0x3d, 0x09, 0xf6,
	0x19, 0xd6, 0xd8, 0x04, 0xf3, 0x8a, 0xcd, 0x1c, 0x63, 0xc7, 0x68, 0xd9, 0x9d, 0xd2, 0xcd, 0x75,
	0x53, 0x41, 0xaa, 0x3e, 0xa4, 0x01, 0x05, 0x2e, 0x9c, 0x02, 0x7a, 0x8a, 0x37, 0xd7, 0xcd, 0x02,
	0x17, 0xb4, 0xc0, 0x85, 0x4a, 0x91, 0x6c, 0xea, 0x98, 0x69, 0x8a, 0x64, 0x53, 0xaa, 0x3e, 0x64,
	0x0b, 0xac, 0x3e, 0x1f, 0x46, 0x8e, 0xb5, 0x63, 0xb4, 0x6a, 0x9d, 0xf2, 0xcd, 0x75, 0x13, 0x31,
	0xc5, 0xaf, 0x57, 0x02, 0xfb, 0x24, 0x10, 0x61, 0xe4, 0x0d, 0x00, 0xce, 0xe6, 0xf2, 0xa2, 0x2b,
	0x7d, 0xca, 0xa6, 0x84, 0x80, 0x75, 0xc9, 0x22, 0xe9, 0x18, 0x3b, 0x66, 0xab, 0x42, 0xf1, 0x4c,
	0x1c, 0x28, 0x61, 0xa3, 0xa7, 0x42, 0xf3, 0xd0, 0x05, 0x24, 0x4f, 0xc0, 0xc6, 0x23, 0x36, 0x56,
	0xdd, 0x7f, 0xd0, 0x4e, 0x97, 0xd0, 0xc6, 0x91, 0xa8, 0xf6, 0x7b, 0xeb, 0x50, 0x4b, 0x48, 0xc4,
	0x38, 0xf2, 0x7c, 0xa8, 0x75, 0x66, 0xbc, 0x37, 0x1c, 0xf4, 0x64, 0xa8, 0x68, 0x33, 0x14, 0xc6,
	0xbf, 0x51, 0x90, 0x0d, 0xb0, 0xa5, 0x60, 0x6c, 0x18, 0xf7, 0xa8, 0x81, 0x57, 0x87, 0xf5, 0x0c,
	0x91, 0xa2, 0x3e, 0x87, 0x7a, 0x6a, 0xe1, 0x3c, 0x50, 0xf4, 0x0d, 0x28, 0xce, 0x38, 0x0f, 0x3e,
	0xbc, 0x43, 0xf6, 0x0a, 0x8d, 0xd1, 0xfd, 0xe7, 0xdb, 0x00, 0xb2, 0x54, 0x54, 0x51, 0x01, 0x94,
	0x15, 0x90, 0x94, 0x4d, 0xbd, 0x6f, 0x06, 0x40, 0x0c, 0xc4, 0x38, 0x22, 0x2f, 0xc1, 0x56, 0x1c,
	0x7a, 0xd1, 0xd5, 0xfd, 0xc7, 0xd9, 0xca, 0x69, 0x98, 0x3e, 0x9e, 0x4c, 0xc2, 0x59, 0x44, 0x75,
	0xbc, 0x7b, 0x10, 0x97, 0x41, 0x23, 0xa9, 0x83, 0x79, 0xc9, 0xa2, 0xb8, 0x6b, 0x75, 0x54, 0x6b,
	0xb8, 0xea, 0x8d, 0xe7, 0x0c, 0x5b, 0x2e, 0x53, 0x0d, 0x0e, 0x0b, 0x07, 0xc6, 0xa1, 0xf5, 0xfd,
	0x47, 0xf3, 0x3f, 0xaf, 0x06, 0x70, 0x3a, 0x19, 0x8f, 0x26, 0x0c, 0xbb, 0xfa, 0x55, 0x80, 0x5a,
	0x02, 0x55, 0x5f, 0xdb, 0x00, 0x17, 0x5c, 0x86, 0xda, 0x86, 0x75, 0x4d, 0x9a, 0xb1, 0x90, 0x2d,
	0xa8, 0x84, 0x03, 0x11, 0xbb, 0x0b, 0xe8, 0x4e, 0x0d, 0xc4, 0x85, 0xf2, 0x57, 0x19, 0x3b, 0x4d,
	0x74, 0x26, 0x98, 0x7c, 0x84, 0xaa, 0x9a, 0x20, 0x66, 0x73, 0x2c, 0x9c, 0xfb, 0x69, 0x76, 0xee,
	0x6c, 0x23, 0x38, 0x79, 0x6c, 0xd0, 0xf3, 0x67, 0xb3, 0xc9, 0x7b, 0x80, 0x60, 0x34, 0x5c, 0xd4,
	0xb2, 0xb1, 0x56, 0xeb, 0xd6, 0x5a, 0xdd, 0x24, 0x54, 0x97, 0xca, 0xe4, 0xba, 0x47, 0x50, 0x5f,
	0xa6, 0xba, 0x6b, 0xab, 0x66, 0x66, 0xab, 0xee, 0x6b, 0xf8, 0x7f, 0xa9, 0x7c, 0x36, 0xdd, 0xbc,
	0x23, 0xdd, 0x5b, 0x83, 0x6a, 0x97, 0x49, 0xd9, 0xf3, 0xf5, 0xff, 0x78, 0x03, 0x6b, 0x29, 0x54,
	0xff, 0x63, 0x0f, 0xca, 0x81, 0xf4, 0xcf, 0xc3, 0x5e, 0xb8, 0xb8, 0x2a, 0x0f, 0xb3, 0x63, 0x76,
	0xb5, 0x8f, 0x26, 0x41, 0xde, 0x29, 0x94, 0x62, 0xa3, 0x12, 0x55, 0x20, 0xfd, 0x4f, 0x91, 0x60,
	0x0b, 0x51, 0xc5, 0x50, 0xf5, 0x33, 0xe0, 0xf3, 0x49, 0x88, 0xfd, 0x58, 0x54, 0x83, 0xbc, 0x82,
	0x8c, 0x58, 0x41, 0xfb, 0x3f, 0x4d, 0xb0, 0x8f, 0x15, 0x19, 0x79, 0x06, 0xd6, 0xd9, 0x68, 0xe2,
	0x93, 0x9c, 0x0c, 0xf0, 0x11, 0x71, 0xff, 0x34, 0x91, 0x5d, 0xb0, 0x8f, 0xc7, 0x5c, 0xb2, 0x7b,
	0x86, 0xbf, 0x82, 0x52, 0xfc, 0x42, 0x90, 0x46, 0x4e, 0x66, 0xc9, 0xdb, 0xe4, 0x3a, 0x2b, 0xed,
	0x6a, 0x4b, 0x6f, 0xa1, 0x92, 0xc8, 0x8f, 0xe4, 0xc2, 0xb2, 0xaf, 0x8c, 0xeb, 0xde, 0xe2, 0x51,
	0x25, 0xba, 0xb0, 0x96, 0x53, 0x30, 0xd9, 0x5a, 0x1d, 0xac, 0x5f, 0x0c, 0x77, 0xfb, 0x2f, 0x5e,
	0x55, 0xee, 0x05, 0xd8, 0x28, 0x53, 0xb2, 0xb1, 0x42, 0xd9, 0x53, 0xb7, 0xb1, 0x5a, 0xef, 0x6a,
	0x0b, 0x8b, 0x2b, 0xde, 0x58, 0x79, 0x9d, 0x97, 0xb6, 0x90, 0xd3, 0xee, 0x11, 0x94, 0x17, 0x97,
	0x87, 0x3c, 0xca, 0xdd, 0x92, 0xf4, 0x86, 0xb9, 0x9b, 0xab, 0x1d, 0x62, 0x1c, 0x75, 0x8a, 0x9f,
	0x2d, 0x7f, 0x26, 0x06, 0xfd, 0x22, 0xbe, 0x69, 0xcf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xba,
	0xfa, 0x32, 0x08, 0xde, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CometClient is the client API for Comet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CometClient interface {
	// Ping Service
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Close Service
	Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// PushMsg push by key or mid
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgReply, error)
	// Broadcast send to every enrity
	Broadcast(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*BroadcastReply, error)
	// BroadcastRoom broadcast to one room
	BroadcastRoom(ctx context.Context, in *BroadcastRoomReq, opts ...grpc.CallOption) (*BroadcastRoomReply, error)
	// Rooms get all rooms
	Rooms(ctx context.Context, in *RoomsReq, opts ...grpc.CallOption) (*RoomsReply, error)
	// Online stats
	Onlines(ctx context.Context, in *OnlinesReq, opts ...grpc.CallOption) (*OnlinesReply, error)
	// Message stats
	Messages(ctx context.Context, in *MessagesReq, opts ...grpc.CallOption) (*MessagesReply, error)
}

type cometClient struct {
	cc *grpc.ClientConn
}

func NewCometClient(cc *grpc.ClientConn) CometClient {
	return &cometClient{cc}
}

func (c *cometClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgReply, error) {
	out := new(PushMsgReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/PushMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Broadcast(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*BroadcastReply, error) {
	out := new(BroadcastReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) BroadcastRoom(ctx context.Context, in *BroadcastRoomReq, opts ...grpc.CallOption) (*BroadcastRoomReply, error) {
	out := new(BroadcastRoomReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/BroadcastRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Rooms(ctx context.Context, in *RoomsReq, opts ...grpc.CallOption) (*RoomsReply, error) {
	out := new(RoomsReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Rooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Onlines(ctx context.Context, in *OnlinesReq, opts ...grpc.CallOption) (*OnlinesReply, error) {
	out := new(OnlinesReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Onlines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Messages(ctx context.Context, in *MessagesReq, opts ...grpc.CallOption) (*MessagesReply, error) {
	out := new(MessagesReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Messages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CometServer is the server API for Comet service.
type CometServer interface {
	// Ping Service
	Ping(context.Context, *Empty) (*Empty, error)
	// Close Service
	Close(context.Context, *Empty) (*Empty, error)
	// PushMsg push by key or mid
	PushMsg(context.Context, *PushMsgReq) (*PushMsgReply, error)
	// Broadcast send to every enrity
	Broadcast(context.Context, *BroadcastReq) (*BroadcastReply, error)
	// BroadcastRoom broadcast to one room
	BroadcastRoom(context.Context, *BroadcastRoomReq) (*BroadcastRoomReply, error)
	// Rooms get all rooms
	Rooms(context.Context, *RoomsReq) (*RoomsReply, error)
	// Online stats
	Onlines(context.Context, *OnlinesReq) (*OnlinesReply, error)
	// Message stats
	Messages(context.Context, *MessagesReq) (*MessagesReply, error)
}

// UnimplementedCometServer can be embedded to have forward compatible implementations.
type UnimplementedCometServer struct {
}

func (*UnimplementedCometServer) Ping(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedCometServer) Close(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (*UnimplementedCometServer) PushMsg(ctx context.Context, req *PushMsgReq) (*PushMsgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMsg not implemented")
}
func (*UnimplementedCometServer) Broadcast(ctx context.Context, req *BroadcastReq) (*BroadcastReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (*UnimplementedCometServer) BroadcastRoom(ctx context.Context, req *BroadcastRoomReq) (*BroadcastRoomReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastRoom not implemented")
}
func (*UnimplementedCometServer) Rooms(ctx context.Context, req *RoomsReq) (*RoomsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rooms not implemented")
}
func (*UnimplementedCometServer) Onlines(ctx context.Context, req *OnlinesReq) (*OnlinesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Onlines not implemented")
}
func (*UnimplementedCometServer) Messages(ctx context.Context, req *MessagesReq) (*MessagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Messages not implemented")
}

func RegisterCometServer(s *grpc.Server, srv CometServer) {
	s.RegisterService(&_Comet_serviceDesc, srv)
}

func _Comet_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Close(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/PushMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).PushMsg(ctx, req.(*PushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Broadcast(ctx, req.(*BroadcastReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_BroadcastRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).BroadcastRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/BroadcastRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).BroadcastRoom(ctx, req.(*BroadcastRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Rooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Rooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Rooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Rooms(ctx, req.(*RoomsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Onlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlinesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Onlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Onlines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Onlines(ctx, req.(*OnlinesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Messages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Messages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Messages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Messages(ctx, req.(*MessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goim.comet.Comet",
	HandlerType: (*CometServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Comet_Ping_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Comet_Close_Handler,
		},
		{
			MethodName: "PushMsg",
			Handler:    _Comet_PushMsg_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _Comet_Broadcast_Handler,
		},
		{
			MethodName: "BroadcastRoom",
			Handler:    _Comet_BroadcastRoom_Handler,
		},
		{
			MethodName: "Rooms",
			Handler:    _Comet_Rooms_Handler,
		},
		{
			MethodName: "Onlines",
			Handler:    _Comet_Onlines_Handler,
		},
		{
			MethodName: "Messages",
			Handler:    _Comet_Messages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
